'use client'
import { Inter } from "next/font/google";
import { createContext, useEffect, useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const AuthContext = createContext();

export default function RootLayout({ children }) {

  const [authenticated, setAuthenticated] = useState(false);
  const [oAuthUser,setOAuthUser] = useState(false);
  const [uniqueId,setUniqueId] = useState('');
  const [username,setUsername] = useState('');

  useEffect(() => {
    const jwtToken = localStorage.getItem('jwtToken');

    if (jwtToken != null) {
      console.log('layout');
      setAuthenticated(true);
    }
  }, []);
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext.Provider value={{authenticated,setAuthenticated}}>
          {children}
        </AuthContext.Provider>
        
      </body>
    </html>
  );
}
